name: editor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_highlighter: ^0.1.1
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.1.0
  highlight: ^0.7.0
  path: ^1.8.3
  system_theme: ^2.3.1
  watcher: ^1.1.0
  window_manager: ^0.3.5
  yaru: ^0.9.0
  yaru_icons: ^1.0.4
  yaru_widgets: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  uses-material-design: true
