name: editor
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  charset: ^2.0.1
  collection: ^1.17.1
  enough_convert: ^1.6.0
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_highlighter: ^0.1.1
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.1.0
  highlight: ^0.7.0
  highlighting: ^0.9.0+11.8.0
  path: ^1.8.3
  recase: ^4.1.0
  shared_preferences: ^2.2.0
  system_theme: ^2.3.1
  watcher: ^1.1.0
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  uses-material-design: true
